name: flutter_ebook_app_clone_riverpod
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  get: ^4.6.5
  flutter_riverpod: ^2.3.6
  google_fonts: 6.1.0 #4.0.0
  pinput: ^3.0.1 #2.2.31
  reactive_forms: ^16.1.0 #15.0.0
  country_code_picker: ^3.0.0
  country_list_picker: ^1.0.2
  blur: ^3.1.0
  flutter_svg: ^2.0.7
  hexcolor: ^3.0.1
  salomon_bottom_bar: ^3.3.2
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  google_nav_bar: ^5.0.6
  flutter_carousel_widget: ^2.0.4
  sliding_up_panel: ^2.0.0+1
  flutter_sliding_up_panel: ^2.0.1
  dio: ^5.2.1+1
  get_it: ^7.6.0
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_secure_storage: ^9.0.0 #8.0.0
  flutter_styled_toast: ^2.1.3
  pretty_dio_logger: ^1.3.1
  device_info_plus: ^9.0.2
  flutter_easyloading: ^3.0.5
  get_storage: ^2.1.1
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.1.12
  image_picker: ^1.0.0
  flutter_local_notifications: 16.1.0
  firebase_messaging: ^14.7.10
  #  firebase_analytics: ^10.8.5
  firebase_analytics: ^10.6.0
  firebase_core: ^2.24.2
  share_plus: ^7.2.1
  google_mobile_ads: ^4.0.0
  shared_preferences: ^2.2.0
  mobile_scanner: ^3.3.0
  geolocator: ^10.1.0
  skeletons: ^0.0.3
  event_bus_plus: ^0.6.1
  #flutter_stripe: ^9.2.2
  flutter_dotenv: ^5.1.0
  intl: ^0.18.0
  fancy_shimmer_image: ^2.0.3
  qr_flutter: ^4.1.0
  audioplayers: ^5.1.0
  socket_io_client: ^2.0.3+1
  upgrader: ^8.0.0
  package_info_plus: ^4.0.1
  #  connectivity_plus: ^5.0.1 #4.0.1
  connectivity_plus: ^4.0.1
  video_player: ^2.7.0
  scroll_snap_list: ^0.9.1
  circular_countdown_timer: ^0.2.3
  new_version_plus: ^0.0.10
  just_audio: ^0.9.36
  loadmore: ^2.1.0
  flutter_screenutil: ^5.9.0
  wakelock_plus: ^1.1.3
  path_provider: ^2.1.1
  flutter_contacts: ^1.1.7+1
  #store_redirect: ^2.0.1
  firebase_dynamic_links: ^5.4.6
  firebase_performance: ^0.9.3+17
  #flutter pub run build_runner build --delete-conflicting-outputs
  #new
  phonepe_payment_sdk: ^1.0.0
  razorpay_flutter: ^1.3.6
  crypto: ^3.0.3
  http: ^1.1.0
  fluttertoast: ^8.2.4
  card_swiper: ^3.0.1
  flutter_slidable: ^3.0.1
  like_button: ^2.0.5
  stylish_bottom_bar: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_gen_runner:
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.1

flutter_icons:
  image_path: "assets/newlogo.jpg"
  android: true
  ios: true
  remove_alpha_ios: true

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background/
    - assets/settings/png/
    - assets/auth/images/
    - assets/settings/svg/
    - assets/settings/svg/bottom_navigation_bar_icon/
    - assets/icons/
    - assets/images/
    - assets/.env
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito-Regular
      fonts:
        - asset: fonts/Nunito-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_gen:
output: lib/gen/ # Optional (default: lib/gen/)
line_length: 80
